// <auto-generated />
using System;
using BotNetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotNetApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517142157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotNetApi.Models.Bot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServicingCustomer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 92,
                            IsOnline = true,
                            IsServicingCustomer = false,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 47.658799999999999,
                            Longitude = -117.426,
                            Name = "BOT-ALPHA",
                            StockLevel = "High"
                        },
                        new
                        {
                            Id = 2,
                            BatteryLevel = 61,
                            IsOnline = true,
                            IsServicingCustomer = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 47.6721,
                            Longitude = -117.3982,
                            Name = "BOT-BRAVO",
                            StockLevel = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            BatteryLevel = 8,
                            IsOnline = false,
                            IsServicingCustomer = false,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 47.654299999999999,
                            Longitude = -117.43899999999999,
                            Name = "BOT-CHARLIE",
                            StockLevel = "Low"
                        },
                        new
                        {
                            Id = 4,
                            BatteryLevel = 77,
                            IsOnline = true,
                            IsServicingCustomer = false,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 47.648899999999998,
                            Longitude = -117.4143,
                            Name = "BOT-DELTA",
                            StockLevel = "High"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
